name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - run: echo "ğŸ‰ Workflow spuÅ¡tÄ›n udÃ¡lostÃ­ ${{ github.event_name }}"
    - run: echo "ğŸ§ Tento job bÄ›Å¾Ã­ na serveru ${{ runner.os }} hostovanÃ©m GitHubem"
    - run: echo "ğŸ” Branch je ${{ github.ref }}, repositÃ¡Å™ ${{ github.repository }}"
    - uses: actions/checkout@v5
    - run: echo "ğŸ’¡ KÃ³d repozitÃ¡Å™e byl zkopÃ­rovÃ¡n do runneru"
    - run: ls ${{ github.workspace }}
    - run: echo "ğŸ Stav jobu je ${{ job.status }}"
